Hitters=na.omit(Hitters)
sum(is.na(Hitters$Salary))
dim(Hitters)
attach(Hitters)

subset.fit=regsubsets(Salary~.,data=Hitters)
subset.fit1=regsubsets(Salary~.,data=Hitters,nvmax = 18)
summary.fit=summary(subset.fit)
plot(subset.fit,scale='Cp')
which.min(summary.fit$cp)
plot(summary.fit$cp)
which.min(summary.fit$bic)
points(6,summary.fit$cp[6],col='red')
length(coef(subset.fit,1:8))
plot(subset.fit)
coef(subset.fit,6)

subset.fit2=regsubsets(Salary~.,data=Hitters,nvmax = 18,method='forward')
summary(subset.fit)
subset.fit3=regsubsets(Salary~.,data=Hitters,nvmax = 18,method='backward')
summary(subset.fit)
i=8
coef(subset.fit1,i)
coef(subset.fit2,i)
coef(subset.fit3,i)
